[package]
name = "rastreador"
version = "0.1.0"
authors = ["darkrye"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = { version = "0.2", default-features = false }
nix = "0.20.0"
